### ISSUE TITLE
Undeclared dependency String::RewritePrefix

### ISSUE THREAD

**Issue by eserte** [doriantaylor/p5-data-grid#1]
Tests fail if String::RewritePrefix is not installed.
List of test reports: http://matrix.cpantesters.org/?dist=Data-Grid
[Statistical analysis](http://analysis.cpantesters.org/solved?distv=Data-Grid-0.04#qr%3A%28Can%27t%20locate%20%5CS%2Bpm%29)

**Comment by doriantaylor** [comment]
yup i've been sucking at releasing modules all week; i just fixed and reissued
